"""alimentary and demographic models updates

Revision ID: 5d5f93263150
Revises: c0c927461472
Create Date: 2022-10-23 16:58:18.253337

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5d5f93263150'
down_revision = 'c0c927461472'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('demographic_profile',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('birth_country', sa.String(length=30), nullable=True),
    sa.Column('birth_city', sa.String(length=30), nullable=True),
    sa.Column('residence_country', sa.String(length=30), nullable=True),
    sa.Column('residence_city', sa.String(length=30), nullable=True),
    sa.Column('residence_seniority', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', name='unique_user_id_demographic')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('unique_user_id_personal', 'personal_profile', type_='unique')
    op.add_column('intolerance', sa.Column('user_id', sa.INTEGER(), nullable=True))
    op.add_column('allergy', sa.Column('user_id', sa.INTEGER(), nullable=True))
    op.drop_constraint('unique_user_id_alimentary', 'alimentary_profile', type_='unique')
    op.drop_table('demographic_profile')
    # ### end Alembic commands ###
