"""personal profile

Revision ID: aa38a7a260fb
Revises: 
Create Date: 2022-10-21 19:45:29.120342

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aa38a7a260fb'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('personal_profile',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=30), nullable=True),
    sa.Column('last_name', sa.String(length=30), nullable=True),
    sa.Column('id_type', sa.Enum('CEDULA_CIUDADANIA', 'CEDULA_EXTRANJERIA', 'NUMERO_ID_PERSONAL', 'NUMERO_ID_TRIBUTARIA', 'TARJETA_IDENTIDAD', 'PASAPORTE', name='idtypeenum'), nullable=True),
    sa.Column('id_number', sa.Integer(), nullable=True),
    sa.Column('genre', sa.Enum('MALE', 'FEMALE', 'N_A', name='genreenum'), nullable=True),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('weight', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', name='unique_user_id_personal')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('personal_profile')
    # ### end Alembic commands ###
