"""models for alimentary profile

Revision ID: c0c927461472
Revises: aa38a7a260fb
Create Date: 2022-10-23 01:23:17.831570

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c0c927461472'
down_revision = 'aa38a7a260fb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alimentary_profile',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('feeding', sa.Enum('VEGETARIANO', 'OMNIVORO', name='feeding'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', name='unique_user_id_alimentary')
    )
    op.create_table('allergy',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('food_allergy', sa.Enum('HUEVOS', 'LECHE_DE_VACA', 'PESCADO_O_MARISCOS', 'FRUTOS_SECOS', 'TRIGO', 'FRUTAS', 'VERDURAS', 'SOJA', name='allergyenum'), nullable=True),
    sa.Column('alimentary_profile_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['alimentary_profile_id'], ['alimentary_profile.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('intolerance',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('food_intolerance', sa.Enum('LACTOSA', 'GLUTEN', 'SACAROSA', 'FRUCTOSA', 'HISTAMINA', 'TRIGO', name='intoleranceenum'), nullable=True),
    sa.Column('alimentary_profile_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['alimentary_profile_id'], ['alimentary_profile.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('intolerance')
    op.drop_table('allergy')
    op.drop_table('alimentary_profile')
    # ### end Alembic commands ###
