"""sport profile model and sport model

Revision ID: e1d482374bd0
Revises: 5d5f93263150
Create Date: 2022-10-27 17:22:27.000797

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e1d482374bd0'
down_revision = '5d5f93263150'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sport_profile',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ftp', sa.Float(), nullable=True),
    sa.Column('vo2_max', sa.Float(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', name='unique_user_id_sport')
    )
    op.create_table('sport',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sport_name', sa.Enum('CYCLING', 'ATHLETICS', name='sportsenum'), nullable=True),
    sa.Column('sport_profile_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['sport_profile_id'], ['sport_profile.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('intolerance', sa.Column('user_id', sa.INTEGER(), nullable=True))
    op.add_column('allergy', sa.Column('user_id', sa.INTEGER(), nullable=True))
    op.drop_table('sport')
    op.drop_table('sport_profile')
    # ### end Alembic commands ###
