name: build

on:
  pull_request:
    branches:
      - master
      - develop
  push:
    branches:
      - '*'

permissions:
  contents: read

jobs:

  pipeline_ic_profile:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Test with pytest
        run: |
          coverage run -m pytest
      - name: Zip coverage report
        run: |
          coverage html
          zip -r coverage.zip htmlcov
      - name: Upload coverage report to GitHub
        if: success() || failure()
        uses: actions/upload-artifact@v3
        with:
          name: coverage.zip
          path: coverage.zip
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
