import enum

CEDULA_CIUDADANIA_ITEM = "CEDULA CIUDADANIA"
CEDULA_EXTRANJERIA_ITEM = "CEDULA EXTRANJERIA"
NUMERO_ID_PERSONAL_ITEM = "NUMERO IDENTIFICACION PERSONAL"
NUMERO_ID_TRIBUTARIA_ITEM = "NUMERO IDENTIFICACION TRIBUTARIA"
TARJETA_IDENTIDAD_ITEM = "TARJETA IDENTIDAD"
PASAPORTE_ITEM = "PASAPORTE"

MALE_ITEM = "HOMBRE"
FEMALE_ITEM = "MUJER"
N_A_ITEM = "N/A"

EGG_ITEM = "HUEVOS"
MILK_ITEM = "LECHE DE VACA"
FISH_ITEM = "PESCADO O MARISCOS"
FRUTOS_SECOS_ITEM = "FRUTOS SECOS"
TRIGO_ITEM = "TRIGO"
FRUITS_ITEM = "FRUTAS"
VEGETABLES_ITEM = "VERDURAS"
SOJA_ITEM = "SOJA"

LACTOSA_ITEM = "LACTOSA"
GLUTEN_ITEM = "GLUTEN"
SACAROSA_ITEM = "SACAROSA"
FRUCTOSA_ITEM = "FRUCTOSA"
HISTAMINA_ITEM = "HISTAMINA"

VEGETARIANO_ITEM = "VEGETARIANO"
OMNIVORO_ITEM = "OMNIVORO"

CYCLING_ITEM = "CICLISMO"
ATHLETICS_ITEM = "ATLETISMO"

SINDROME_PALETOFEMORAL_ITEM = "SINDROME PALETOFEMORAL"
ROTULA_ITEM = "ROTULA"
TENDINITIS_ITEM = "TENDINITIS"
SINDROME_PLICA_MEDIAL_ITEM = "SINDROME DE LA PLICA MEDIAL"
SINDROME_BANDA_ILIOTIBIAL_ITEM = "SINDROME DE FRICCION DE LA BANDA ILIOTIBIAL"
OTRA_ITEM = "OTRA"
NINGUNA_ITEM = "NINGUNA"

TORCEDURAS_DISTENSIONES_ITEM = "TORCEDURAS Y DISTENSIONES"
LESIONES_RODILLA_ITEM = "LESIONES DE RODILLA"
INFLAMACION_MUSCULAR_ITEM = "INFLAMACION MUSCULAR"
TRAUMATISMOS_TENDON_AQUILES_ITEM = "TRAUMATISMOS EN EL TENDÓN DE AQUILES"
DOLOR_HUESO_TIBIA_ITEM = "DOLOR EN EL HUESO DE LA TIBIA"
LESIONES_MANGUITO_ROTATORIO_ITEM = "LESIONES DEL MANGUITO ROTATORIO DEL HOMBRO"
FRACTURAS_ITEM = "FRACTURAS"
DISLOCACIONES_ITEM = "DISLOCACIONES"


class AllergyEnum(enum.Enum):
    HUEVOS = EGG_ITEM
    LECHE_DE_VACA = MILK_ITEM
    PESCADO_O_MARISCOS = FISH_ITEM
    FRUTOS_SECOS = FRUTOS_SECOS_ITEM
    TRIGO = TRIGO_ITEM
    FRUTAS = FRUITS_ITEM
    VERDURAS = VEGETABLES_ITEM
    SOJA = SOJA_ITEM

    def __str__(self):
        return self.value


class IntoleranceEnum(enum.Enum):
    LACTOSA = LACTOSA_ITEM
    GLUTEN = GLUTEN_ITEM
    SACAROSA = SACAROSA_ITEM
    FRUCTOSA = FRUCTOSA_ITEM
    HISTAMINA = HISTAMINA_ITEM
    TRIGO = TRIGO_ITEM

    def __str__(self):
        return self.value


class GenreEnum(enum.Enum):
    MALE = MALE_ITEM
    FEMALE = FEMALE_ITEM
    N_A = N_A_ITEM

    def __str__(self):
        return self.value


class IdTypeEnum(enum.Enum):
    CEDULA_CIUDADANIA = CEDULA_CIUDADANIA_ITEM
    CEDULA_EXTRANJERIA = CEDULA_CIUDADANIA_ITEM
    NUMERO_ID_PERSONAL = NUMERO_ID_PERSONAL_ITEM
    NUMERO_ID_TRIBUTARIA = NUMERO_ID_TRIBUTARIA_ITEM
    TARJETA_IDENTIDAD = TARJETA_IDENTIDAD_ITEM
    PASAPORTE = PASAPORTE_ITEM

    def __str__(self):
        return self.value


class FeedingEnum(enum.Enum):
    VEGETARIANO = VEGETARIANO_ITEM
    OMNIVORO = OMNIVORO_ITEM

    def __str__(self):
        return self.value


class SportsEnum(enum.Enum):
    CYCLING = CYCLING_ITEM
    ATHLETICS = ATHLETICS_ITEM

    def __str__(self):
        return self.value


class InjuryEnum(enum.Enum):
    SINDROME_PALETOFEMORAL = SINDROME_PALETOFEMORAL_ITEM
    ROTULA = ROTULA_ITEM
    TENDINITIS = TENDINITIS_ITEM
    SINDROME_PLICA_MEDIAL = SINDROME_PLICA_MEDIAL_ITEM
    SINDROME_BANDA_ILIOTIBIAL = SINDROME_BANDA_ILIOTIBIAL_ITEM
    OTRA = OTRA_ITEM
    NINGUNA = NINGUNA_ITEM

    TORCEDURAS_DISTENSIONES = TORCEDURAS_DISTENSIONES_ITEM
    LESIONES_RODILLA = LESIONES_RODILLA_ITEM
    INFLAMACION_MUSCULAR = INFLAMACION_MUSCULAR_ITEM
    TRAUMATISMOS_TENDON_AQUILES = TRAUMATISMOS_TENDON_AQUILES_ITEM
    DOLOR_HUESO_TIBIA = DOLOR_HUESO_TIBIA_ITEM
    LESIONES_MANGUITO_ROTATORIO = LESIONES_MANGUITO_ROTATORIO_ITEM
    FRACTURAS = FRACTURAS_ITEM
    DISLOCACIONES = DISLOCACIONES_ITEM

    def __str__(self):
        return self.value
