import enum

CEDULA_CIUDADANIA_ITEM = "CEDULA CIUDADANIA"
CEDULA_EXTRANJERIA_ITEM = "CEDULA EXTRANJERIA"
NUMERO_ID_PERSONAL_ITEM = "NUMERO IDENTIFICACION PERSONAL"
NUMERO_ID_TRIBUTARIA_ITEM = "NUMERO IDENTIFICACION TRIBUTARIA"
TARJETA_IDENTIDAD_ITEM = "TARJETA IDENTIDAD"
PASAPORTE_ITEM = "PASAPORTE"

MALE_ITEM = "HOMBRE"
FEMALE_ITEM = "MUJER"
N_A_ITEM = "N/A"

EGG_ITEM = "HUEVOS"
MILK_ITEM = "LECHE DE VACA"
FISH_ITEM = "PESCADO O MARISCOS"
FRUTOS_SECOS_ITEM = "FRUTOS SECOS"
TRIGO_ITEM = "TRIGO"
FRUITS_ITEM = "FRUTAS"
VEGETABLES_ITEM = "VERDURAS"
SOJA_ITEM = "SOJA"

LACTOSA_ITEM = "LACTOSA"
GLUTEN_ITEM = "GLUTEN"
SACAROSA_ITEM = "SACAROSA"
FRUCTOSA_ITEM = "FRUCTOSA"
HISTAMINA_ITEM = "HISTAMINA"

VEGETARIANO_ITEM = "VEGETARIANO"
OMNIVORO_ITEM = "OMNIVORO"

CYCLING_ITEM = "CICLISMO"
ATHLETICS_ITEM = "ATLETISMO"


class AllergyEnum(enum.Enum):
    HUEVOS = EGG_ITEM
    LECHE_DE_VACA = MILK_ITEM
    PESCADO_O_MARISCOS = FISH_ITEM
    FRUTOS_SECOS = FRUTOS_SECOS_ITEM
    TRIGO = TRIGO_ITEM
    FRUTAS = FRUITS_ITEM
    VERDURAS = VEGETABLES_ITEM
    SOJA = SOJA_ITEM

    def __str__(self):
        return self.value


class IntoleranceEnum(enum.Enum):
    LACTOSA = LACTOSA_ITEM
    GLUTEN = GLUTEN_ITEM
    SACAROSA = SACAROSA_ITEM
    FRUCTOSA = FRUCTOSA_ITEM
    HISTAMINA = HISTAMINA_ITEM
    TRIGO = TRIGO_ITEM

    def __str__(self):
        return self.value


class GenreEnum(enum.Enum):
    MALE = MALE_ITEM
    FEMALE = FEMALE_ITEM
    N_A = N_A_ITEM

    def __str__(self):
        return self.value


class IdTypeEnum(enum.Enum):
    CEDULA_CIUDADANIA = CEDULA_CIUDADANIA_ITEM
    CEDULA_EXTRANJERIA = CEDULA_CIUDADANIA_ITEM
    NUMERO_ID_PERSONAL = NUMERO_ID_PERSONAL_ITEM
    NUMERO_ID_TRIBUTARIA = NUMERO_ID_TRIBUTARIA_ITEM
    TARJETA_IDENTIDAD = TARJETA_IDENTIDAD_ITEM
    PASAPORTE = PASAPORTE_ITEM

    def __str__(self):
        return self.value


class FeedingEnum(enum.Enum):
    VEGETARIANO = VEGETARIANO_ITEM
    OMNIVORO = OMNIVORO_ITEM

    def __str__(self):
        return self.value


class SportsEnum(enum.Enum):
    CYCLING = CYCLING_ITEM
    ATHLETICS = ATHLETICS_ITEM

    def __str__(self):
        return self.value
